#!/usr/bin/env bash
# bootstrap.sh — generate hex secrets and write per-host .env files for LATTICE.
#
# Idempotent: refuses to overwrite an existing .env. Safe to re-run.
# Run from repo root or anywhere — paths are resolved relative to this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

MAC_MINI_ENV="${REPO_ROOT}/hosts/mac-mini/.env"
COLTONS_MAC_ENV="${REPO_ROOT}/hosts/coltons-mac/.env"

gen_hex() {
  python3 -c "import secrets; print(secrets.token_hex(16))"
}

write_mac_mini_env() {
  if [[ -f "${MAC_MINI_ENV}" ]]; then
    echo "[skip] ${MAC_MINI_ENV} already exists — not overwriting."
    return
  fi
  local admin_token edith_secret raven_secret voice_secret
  admin_token="$(gen_hex)"
  edith_secret="$(gen_hex)"
  raven_secret="$(gen_hex)"
  voice_secret="$(gen_hex)"
  cat > "${MAC_MINI_ENV}" <<EOF
# Generated by scripts/bootstrap.sh — never commit this file.
ADMIN_TOKEN=${admin_token}
EDITH_SECRET=${edith_secret}
RAVEN_SECRET=${raven_secret}
VOICE_SECRET=${voice_secret}
ANTHROPIC_API_KEY=
# OPENAI_API_KEY powers the voice node (gpt-realtime-2). Without it
# voice.start_session returns openai_key_missing; the node still registers
# and the inspector at :8807 still loads.
OPENAI_API_KEY=
CORE_URL=http://100.109.10.50:8000
EOF
  chmod 600 "${MAC_MINI_ENV}"
  echo "[ok]   wrote ${MAC_MINI_ENV}"
  echo "       (fill in ANTHROPIC_API_KEY before booting EDITH)"
  echo "       (fill in OPENAI_API_KEY before starting a voice session)"
}

write_coltons_mac_env() {
  if [[ -f "${COLTONS_MAC_ENV}" ]]; then
    echo "[skip] ${COLTONS_MAC_ENV} already exists — not overwriting."
    return
  fi
  local control_secret
  control_secret="$(gen_hex)"
  cat > "${COLTONS_MAC_ENV}" <<EOF
# Generated by scripts/bootstrap.sh — never commit this file.
CONTROL_SECRET=${control_secret}
CORE_URL=http://100.109.10.50:8000
EOF
  chmod 600 "${COLTONS_MAC_ENV}"
  echo "[ok]   wrote ${COLTONS_MAC_ENV}"
}

echo "LATTICE bootstrap — generating per-host .env files"
echo "repo root: ${REPO_ROOT}"
echo

write_mac_mini_env
write_coltons_mac_env

echo
echo "Done. Next steps:"
echo "  1. Fill in ANTHROPIC_API_KEY in hosts/mac-mini/.env (or use OAuth: scripts/refresh-oauth-token.sh)"
echo "  2. On Mac mini:     ./hosts/mac-mini/start-core.sh"
echo "  3. On Mac mini:     cd nodes/edith && docker compose up"
echo "  4. On Mac mini:     cd nodes/raven && ./start.sh"
echo "  5. On Mac mini:     scripts/quickstart_voice.sh   (optional, needs OPENAI_API_KEY)"
echo "  6. On Colton's Mac: see nodes/control/README.md"
